//! Words commonly capitalized at sentence start in English prose. Kept
//! curated rather than open-ended; anything outside this list (and the
//! profile's employer / project / skill token sets, and the original
//! bullet's proper-noun set) is treated as a candidate invented proper
//! noun. The list bundles two categories:
//!
//! 1. Sentence connectors / pronouns (`The`, `And`, `That`, ...). Almost
//!    every English bullet that doesn't lead with a verb leads with one
//!    of these.
//! 2. Common resume-action verbs (`Built`, `Architected`, `Engineered`,
//!    `Optimized`, `Migrated`, ...). The LLM legitimately picks from
//!    the standard resume-verb thesaurus, and these get sentence-start
//!    capitalization automatically. Without them the guardrail
//!    false-rejects rewords whose lead verb wasn't in the original
//!    seed list of seven.
//! 3. Common sentence-start adjectives / participles (`Experienced`,
//!    `Skilled`, `Proficient`, ...). Summary rewrites lead with these;
//!    they are ordinary English, not invented entities.

pub(crate) const COMMON_ENGLISH_CAPS: &[&str] = &[
    // --- connectors / pronouns / determiners ---
    "the",
    "and",
    "for",
    "with",
    "that",
    "this",
    "into",
    "from",
    "over",
    "when",
    "where",
    "which",
    "while",
    "after",
    "during",
    "using",
    "through",
    "also",
    "their",
    "these",
    "those",
    "such",
    "each",
    "every",
    "some",
    "any",
    "both",
    "either",
    "neither",
    "many",
    "most",
    "several",
    "few",
    // --- temporal / sequence adverbs (common at sentence start) ---
    "currently",
    "previously",
    "recently",
    "today",
    "yesterday",
    "now",
    "then",
    "later",
    "earlier",
    "first",
    "second",
    "third",
    "fourth",
    "fifth",
    "initially",
    "finally",
    "lastly",
    "eventually",
    "subsequently",
    "simultaneously",
    "since",
    "until",
    "before",
    // --- frequency / qualifier adverbs ---
    "successfully",
    "additionally",
    "furthermore",
    "moreover",
    "however",
    "therefore",
    "thus",
    "hence",
    "specifically",
    "particularly",
    "generally",
    "typically",
    "usually",
    "frequently",
    "occasionally",
    "always",
    "often",
    "sometimes",
    "rarely",
    "never",
    "consistently",
    "deeply",
    "directly",
    "primarily",
    // --- resume-action verbs ---
    "built",
    "led",
    "shipped",
    "drove",
    "designed",
    "implemented",
    "owned",
    "delivered",
    "architected",
    "engineered",
    "developed",
    "deployed",
    "optimized",
    "migrated",
    "refactored",
    "scaled",
    "automated",
    "integrated",
    "established",
    "achieved",
    "reduced",
    "increased",
    "coordinated",
    "mentored",
    "spearheaded",
    "defined",
    "authored",
    "modernized",
    "hardened",
    "instrumented",
    "profiled",
    "tuned",
    "accelerated",
    "parallelized",
    "decoupled",
    "simplified",
    "managed",
    "executed",
    "transformed",
    "validated",
    "prototyped",
    "championed",
    "partnered",
    "collaborated",
    "contributed",
    "supported",
    "enabled",
    "drafted",
    "presented",
    "analyzed",
    "investigated",
    "diagnosed",
    "resolved",
    "rewrote",
    "rolled",
    "rolled-out",
    "rolled-back",
    "promoted",
    "expanded",
    "consolidated",
    "documented",
    "tested",
    "benchmarked",
    "monitored",
    "enforced",
    "secured",
    "audited",
    "ported",
    "packaged",
    "released",
    "configured",
    "ramped",
    "kicked",
    "saved",
    "trimmed",
    "fixed",
    "patched",
    "added",
    "removed",
    "replaced",
    "introduced",
    "improved",
    "raised",
    "doubled",
    "tripled",
    "halved",
    "tracked",
    "received",
    "stabilized",
    // --- common sentence-start adjectives / participles ---
    // Summary rewrites often lead with an adjective ("Experienced in
    // embedded Linux..."), capitalized at sentence start like any
    // proper noun. These are normal English, not invented entities;
    // without them the guardrail false-rejects otherwise compliant
    // rewrites (regression: live tailoring rejected a summary reword
    // for the word "Experienced").
    "experienced",
    "skilled",
    "proficient",
    "seasoned",
    "passionate",
    "dedicated",
];
