//! Config generation module — builds exhaustive `config/local.yaml`
//! from a candidate [`Profile`] and domain defaults.

use crate::schema::Profile;

/// Generate a complete `config/local.yaml` string from candidate profile data.
#[must_use]
pub fn generate_config_yaml(profile: &Profile) -> String {
    let mut p1_keywords: Vec<String> = vec![
        "Embedded Software Engineer".into(),
        "Embedded Systems".into(),
        "Device Driver".into(),
        "Linux Kernel".into(),
        "Yocto".into(),
        "RTOS".into(),
        "ROS / ROS2".into(),
        "Robotics".into(),
        "Drone Flight Controller".into(),
        "Computer Vision / Camera".into(),
        "Video Streaming / H.264 / RTSP".into(),
        "Radio / WiFi / Bluetooth / BLE".into(),
        "AI / ML Engineer".into(),
        "Deep Learning / PyTorch".into(),
        "Edge AI / TensorRT / ONNX".into(),
        "DSP / Signal Processing".into(),
    ];

    let p2_keywords: Vec<String> = vec![
        "Software Engineer".into(),
        "Fullstack Developer".into(),
        "Backend Developer".into(),
        "Rust Developer".into(),
        "Python Engineer".into(),
        "C/C++ Developer".into(),
        "Web Developer / React / Node.js".into(),
        "REST API / Microservices".into(),
    ];

    let p3_keywords: Vec<String> = vec![
        "Electronics & Telecommunications".into(),
        "RF Engineering".into(),
        "Wireless Communications".into(),
        "Mathematics & Physics Algorithms".into(),
        "Control Systems".into(),
    ];

    // Extract skills from candidate profile
    for lang in &profile.skills.languages {
        if !lang.trim().is_empty() && !p1_keywords.contains(lang) {
            p1_keywords.push(lang.clone());
        }
    }
    for framework in &profile.skills.frameworks {
        if !framework.trim().is_empty() && !p1_keywords.contains(framework) {
            p1_keywords.push(framework.clone());
        }
    }
    for tool in &profile.skills.tools {
        if !tool.trim().is_empty() && !p1_keywords.contains(tool) {
            p1_keywords.push(tool.clone());
        }
    }

    let mut locations = vec!["Remote".to_string()];
    if !profile.personal.location.trim().is_empty() {
        locations.push(profile.personal.location.clone());
    }
    locations.push("Gurugram".into());
    locations.push("India".into());

    format!(
        r#"# Local Configuration generated by career-ai
version: "1.0"

llm:
  backend: "api"
  provider: "deepseek"
  model: "deepseek-chat"
  api_base_url: "https://api.deepseek.com/v1"
  api_key: "sk-deepseekapi"
  parse_resume_model: "deepseek-chat"
  tailor_model: "deepseek-chat"
  timeout_seconds: 300

sources:
  keywords:
{}
  locations:
{}

scheduler:
  cadence:
    greenhouse: "0 0 */1 * * *"
    lever: "0 0 */1 * * *"
    remotive: "0 0 */2 * * *"
    naukri: "0 15 */3 * * *"
    linkedin: "0 0 */4 * * *"
    indeed: "0 30 */4 * * *"

filter:
  remote_preference: "remote_first"
  contract_type: "all"  # options: all, full_time, freelance_contract
  min_score_threshold: 0.04
"#,
        format_list(&p1_keywords, &p2_keywords, &p3_keywords),
        format_locations(&locations)
    )
}

fn format_list(p1: &[String], p2: &[String], p3: &[String]) -> String {
    let mut out = String::new();
    out.push_str("    # Priority 1: AI/ML, Embedded Systems, Robotics, Drones, Camera, Video, Radio/WiFi\n");
    for k in p1 {
        out.push_str(&format!("    - \"{k}\"\n"));
    }
    out.push_str("    # Priority 2: Fullstack & Software Development\n");
    for k in p2 {
        out.push_str(&format!("    - \"{k}\"\n"));
    }
    out.push_str("    # Priority 3: STEM, Telecommunications, Physics & Math\n");
    for k in p3 {
        out.push_str(&format!("    - \"{k}\"\n"));
    }
    out
}

fn format_locations(locs: &[String]) -> String {
    let mut out = String::new();
    for l in locs {
        out.push_str(&format!("    - \"{l}\"\n"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::Profile;

    #[test]
    fn test_generate_config_yaml() {
        let mut p = Profile::default();
        p.skills.languages = vec!["Rust".into(), "C++".into()];
        let yaml = generate_config_yaml(&p);
        assert!(yaml.contains("Embedded Software Engineer"));
        assert!(yaml.contains("Rust"));
        assert!(yaml.contains("Gurugram"));
    }
}
